Проект 13 спринта
AlexandraLesnykh/java-shareit pull request #2
Opened 2023-02-16 11:37 UTC by AlexandraLesnykh

2023-02-16 19:58 UTC, AlexandraLesnykh commented
Проект 13 спринта. Итерация 1

2023-02-17 17:42 UTC, db-exp requested changes

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    int id;
лучше Long - для идентификаторов в реальных системах из-за размерности int не используют

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        SqlRowSet itemRows = jdbcTemplate.queryForRowSet("SELECT * FROM items WHERE item_id= ?", id);
тут лучше подойдет jdbcTemplate.queryForObject - мы же ищем один объект или пустоту

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item create(Item item, int ownerId) throws ValidationException {
в формате можно лучше - обычно в таких методах используют аннотацию Transactional

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item update(ItemDto itemDto, int id, int ownerId) {
тут тоже можно Transactional (можно лучше)

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        int checkUserId = jdbcTemplate.queryForObject("SELECT COUNT(user_id) FROM users WHERE user_id=?", Integer.class, ownerId);
давай проверку на наличие просто в отдельный метод вынесем и переиспользуем и тут и в update

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (!text.equals("")) {
лучше isEmpty/isBlank

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    int id;
лучше Long

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    int id;
Лучше Long

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    int id;
лучше Long

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    int requestor;
лучше Long

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
> +    int id;
лучше Long

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        SqlRowSet userRows = jdbcTemplate.queryForRowSet("SELECT * FROM users WHERE user_id= ?", id);
запросы к БД в контроллере лучше не делать - происходит перемешивание слоев

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        SqlRowSet userRows = jdbcTemplate.queryForRowSet("SELECT * FROM users WHERE user_id= ?", id);
Давай вынесем в сервис и используем queryForObject

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User create(@RequestBody @Valid User user) throws ValidationException {
вынеси, пожалуйста, весь sql в сервис

2023-02-17 17:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User update(@RequestBody @NotNull @Valid UserDto user, @PathVariable("id") @NotNull Integer id) {
тоже самое - давай вынесем sql )

2023-02-17 18:57 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto {
Сделано

2023-02-17 18:58 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    int id;
Сделано

2023-02-17 18:59 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        SqlRowSet itemRows = jdbcTemplate.queryForRowSet("SELECT * FROM items WHERE item_id= ?", id);
Сделано

2023-02-17 19:00 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item create(Item item, int ownerId) throws ValidationException {
Это мы проходим в следующем спринте)

2023-02-17 19:14 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        int checkUserId = jdbcTemplate.queryForObject("SELECT COUNT(user_id) FROM users WHERE user_id=?", Integer.class, ownerId);
Сделано

2023-02-17 19:15 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (!text.equals("")) {
Сделано

2023-02-17 19:19 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    int id;
Сделано

2023-02-17 19:19 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    int id;
Сделано

2023-02-17 19:20 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/User.java
> +    int id;
Сделано

2023-02-17 19:41 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        SqlRowSet userRows = jdbcTemplate.queryForRowSet("SELECT * FROM users WHERE user_id= ?", id);
Сделано

2023-02-17 19:47 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User update(@RequestBody @NotNull @Valid UserDto user, @PathVariable("id") @NotNull Integer id) {
Рефакторинг сделан

2023-02-17 21:52 UTC, AlexandraLesnykh commented
Выполнен рефакторинг кода UserController, изменен тип переменной id на long

2023-02-17 23:57 UTC, db-exp approved these changes

2023-03-08 18:42 UTC, merged