Add bookings
AlexandraLesnykh/java-shareit pull request #3
Opened 2023-03-05 10:49 UTC by AlexandraLesnykh

2023-03-05 10:57 UTC, AlexandraLesnykh commented
Проект 14 спринта.

2023-03-05 18:32 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new ValidationException("f");
f ) ?

2023-03-05 19:16 UTC, db-exp requested changes

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/comments/model/Comment.java
> +    String text;
лучше явно писать Size

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
нужно добавить аннотацию Repository

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  public class ItemRequest {
Если мы используем Valid и хотим получать от него пользу, то нужно явно проставить аннотации на полях dto запроса, что будет ок - например, Size/Not  blank  для description, NonNull итп

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
> +
лишняя строка

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
не хватает аннотации Repository

2023-03-05 19:16 UTC, db-exp commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./db/java-shareit
postgresql для работы, а h2 для тестов

2023-03-05 19:16 UTC, db-exp commented on src/main/resources/schema.sql
> +                                       text varchar NOT NULL,
text это тип в postgresql, лучше как-то еще назвать, чтобы не путать и дополнительно нужно указать а сколько тут в varchar

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User update(@RequestBody @NotNull @Valid User user, @PathVariable("id") @NotNull Long id) {
NonNull тут на поля внутри лучше поставить

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
тут не нужен

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private List<String> emails = new ArrayList<>();
лучше не надо так - код становится не особо надежный при многопоточности - правильней - проверять уникальность по базе

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item update(@RequestBody @NotNull @Valid ItemDto item, @PathVariable("id") @NotNull Long id,
NonNull лучше внутри Dto использовать на полях

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto addComment(@RequestBody @NotNull @Valid Comment comment, @PathVariable("id") @NotNull Long id,
Лучше использовать NonNull внутри Dto

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
как и в других сервисах - тут не стоит обращаться через jdbcTermplate к базе, для этого есть репозиторий, там можно использовать Query аннотацию в случае нестандартного findBy запроса или если запрос совсем сложный, то jdbcTemplate вызывать (но на уровне репозитория, а не сервиса)

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } catch (NullPointerException e) {
нельзя ловить NPE - нужно лечить причину

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            } catch (NullPointerException exception) {
нельзя ловить NPE

2023-03-05 19:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    throw new NullPointerException();
лучше бросить Validation или Runtime итп

2023-03-05 20:59 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new ValidationException("f");
Бес попутал)
Исправила.

2023-03-05 21:02 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        listForReturn.clear();
Исправлено

2023-03-05 21:03 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingForReturn.clear();
Исправлено

2023-03-07 10:28 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        response.setContentType("text/html");
Исправила этот момент везде. И ownerId по-другому стала получать: через аннотацию

2023-03-07 10:40 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            switch (state) {
Насколько оправдано создавать новый класс enum, вбивая в него варианты все равно руками? Пока оставила так. Если считаешь, что грамотнее через enum, на следующей итерации исправлю)

2023-03-07 11:11 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private Item findItem(Long id) {
Сделано

2023-03-07 11:11 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        long checkUserId = jdbcTemplate.queryForObject("SELECT COUNT (id) FROM users WHERE id=?", Long.class, ownerId);
Сделано

2023-03-07 11:11 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        boolean checkAvailable = jdbcTemplate.queryForObject("SELECT available FROM items WHERE id=?", Boolean.class, booking.getItemId());
Сделано

2023-03-07 11:12 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Исправлено

2023-03-07 11:29 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Transient
Решила использовать эту аннотацию, чтобы не сериализовать эти объекты в БД. То есть экземпляры Item item и User user в данном случае мне нужны, чтобы внести их в BookingDto. 
вот что в интернете пишут:
Свойства класса, помеченные модификатором transient, не сериализуются.

Обычно в таких полях хранится промежуточное состояние объекта, которое, к примеру, проще вычислить, чем сериализовать, а затем десериализовать. Другой пример такого поля — ссылка на экземпляр объекта, который не требует сериализации или не может быть сериализован.

2023-03-07 11:32 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/comments/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
Добавлена

2023-03-07 11:32 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
Добавлена

2023-03-07 11:32 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Добавлена

2023-03-07 14:43 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        response.setContentType("text/html");
Исправила здесь и в других контроллерах.

2023-03-07 14:44 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Сделано

2023-03-07 14:45 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/comments/model/Comment.java
> +    String text;
Сделано

2023-03-07 14:47 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  public class ItemRequest {
Добавила аннотации. 
Но этот класс в этом спринте мы пока не использовали)

2023-03-07 14:47 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/User.java
> +
Исправлено

2023-03-07 14:51 UTC, AlexandraLesnykh commented on src/main/resources/schema.sql
> +                                       text varchar NOT NULL,
Исправила

2023-03-07 15:00 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User update(@RequestBody @NotNull @Valid User user, @PathVariable("id") @NotNull Long id) {
Исправила

2023-03-07 15:01 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item update(@RequestBody @NotNull @Valid ItemDto item, @PathVariable("id") @NotNull Long id,
Сделано

2023-03-07 15:02 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        listForReturn.clear();
Сделанл

2023-03-07 15:05 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Исправлено

2023-03-07 15:14 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingForReturn.clear();
Исправлено

2023-03-07 15:17 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Booking findFirstByItemIdAndStatusAndEndBeforeOrderByEnd(long itemId, BookingStatus bookingStatus, LocalDateTime now);
Сделано

2023-03-08 07:37 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Сделано

2023-03-08 07:38 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        response.setContentType("text/html");
Сделано

2023-03-08 07:38 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private List<String> emails = new ArrayList<>();
Исправлено

2023-03-08 07:39 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        listForReturn.clear();
Сделанл

2023-03-08 07:39 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingForReturn.clear();
Исправлено

2023-03-08 13:34 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto addComment(@RequestBody @NotNull @Valid Comment comment, @PathVariable("id") @NotNull Long id,
Сделано

2023-03-08 13:34 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Сделано

2023-03-08 13:34 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } catch (NullPointerException e) {
Исправила

2023-03-08 13:34 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            } catch (NullPointerException exception) {
Исправила

2023-03-08 13:34 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    throw new NullPointerException();
Исправила

2023-03-08 18:48 UTC, AlexandraLesnykh commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./db/java-shareit
Сделано

2023-03-08 18:48 UTC, AlexandraLesnykh commented
Итерация 2.

2023-03-09 08:13 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
лишние строчки

2023-03-09 09:58 UTC, db-exp requested changes

2023-03-09 09:58 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : allItems) {
лучше по базе делать через like ("можно лучше")

2023-03-09 09:58 UTC, db-exp commented on pom.xml
> +            <artifactId>cdi-api</artifactId>
для чего используется?  тут вроде нет в нем необходимости

2023-03-09 09:58 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setItem(itemRepository.findById(booking.getItemId()).get());
может тоже стоить бросать ошибку если не нашли, а то будет NPE
тут и во всех сервисах с получением айтема

2023-03-09 09:58 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setUser(userRepository.findById(booking.getBookerId()).get());
может тоже стоить бросать ошибку если не нашли, а то будет NPE
тут и во всех сервисах с получением пользователя

2023-03-09 13:01 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
Исправлено

2023-03-09 13:06 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/comments/model/Comment.java
> +
Испоавлено

2023-03-09 13:16 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setItem(itemRepository.findById(booking.getItemId()).get());
В данном случае item проверяется раньше на 2 строки в методе checkIdsWhileCreate

2023-03-09 13:17 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setUser(userRepository.findById(booking.getBookerId()).get());
Проверку юзера так же добавила в метод checkIdsWhileCreate

2023-03-09 13:23 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setUser(userRepository.findById(booking.getBookerId()).get());
Добавила проверку

2023-03-09 19:35 UTC, db-exp requested changes

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setUser(userRepository.findById(booking.getBookerId()).get());
а если не найдем пользователя? может тоже лучше throw new ObjectNotFoundException("Wrong id");

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setUser(userRepository.findById(booking.getBookerId()).get());
может добавить throw new ObjectNotFoundException("Wrong id"); ?

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setUser(userRepository.findById(booking.getBookerId()).get());
Другой вариант, чтобы постоянно не обкладываться такими записями - вызывать сервис, а внутри метода сервиса один раз обернуть

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setItem(itemRepository.findById(booking.getItemId()).get());
и тут

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setItem(itemRepository.findById(booking.getItemId()).get());
и тут

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setUser(userRepository.findById(booking.getBookerId()).get());
и тут

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        boolean checkAvailable = itemRepository.findById(booking.getItemId()).get().isAvailable();
и тут

2023-03-09 19:35 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setItem(itemRepository.findById(booking.getItemId()).get());
ты права, но это как пример - давай сервис просто вызовем? можно в следующем спринте
то есть в itemService, userService в методе findBy сделать проверку и все - получаем более компактный код

2023-03-09 21:42 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setItem(itemRepository.findById(booking.getItemId()).get());
Сделано. 
добавила вызов сервисов вместо вызова репозитория. В самих сервисах проверка тоже соответственно присутствует

2023-03-09 21:44 UTC, AlexandraLesnykh commented
Сервисы вызваны в нужных местах)

2023-03-10 07:40 UTC, db-exp approved these changes

2023-03-10 07:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>      private final UserRepository userRepository;
если вызываем сервисы - репозитории не нужны
UserRepository
ItemRepository

2023-04-19 22:33 UTC, merged